name: Build and Deploy
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Build to firebase'
        required: true
        default: 'Mona the Octocat'
      home:
        description: 'location'
        required: false

jobs:
  deploy: 
    name: Build & Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 10.x ]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v1

      - name: Get Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Get PWD
        run: |
          echo $PWD
          ls -halt

      - name: Install dependencies
        run: npm install
        working-directory: ./projects/functions
      
      - name: Deploy
        run: npx firebase deploy
        working-directory: ./projects/functions